name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish --no-build -o artifacts
    - name: GH Pages deploy
      uses: Cecilapp/GitHub-Pages-deploy@3.1.0
      with:
        # A verified email.
        email: ericm@remphoto.net
        # Where static files are.
        build_dir: artifacts
        # Which branch to push files.
        branch: gh-pages
        # The custom domain name.
        cname: tektonic.kanyon.dev
